### ISSUE TITLE
are tables on the roadmap?

### ISSUE THREAD

**Issue by timotheecour** [soasme/nim-markdown#3]
See also: https://github.com/nim-lang/Nim/issues/9291#issuecomment-431698702

@GULPF
> IMO if Nim is going to switch to markdown, there first must be a pure Nim implementation. Preferable one that implements a well specified form of markdown like CommonMark (note however that commonmark does not support anything fancy like tables).

IMO support for tables is a must, even if CommonMark doesn't support them.

**Comment by soasme** [comment]
Thanks for the feedback. I've just bumped version from 0.2.0 to [0.3.0](https://github.com/soasme/nim-markdown/blob/07a7808558040229117217b51eb327f38a2aae79/tests/testmarkdown.nim#L171-L208) for the table support. However, due to [the ongoing GitHub issue](https://status.github.com/messages), it's not showing on the GitHub page. Will close the issue when v0.3.0 appears in the master repo.

**Comment by soasme** [comment]
[v0.3.0](https://github.com/soasme/nim-markdown/tree/v0.3.0) is published. :)
