### ISSUE TITLE
Strikethrough in list doesn't work

### ISSUE THREAD

**Issue by metagn** [soasme/nim-markdown#43]
```nim
import markdown

echo markdown("* ~~da~~")
```

Output:

```
<ul>
<li>~~da~~</li>
</ul>
```

**Comment by soasme** [comment]
Hi @hlaaftana ,

Thanks for reporting. This is an expected behavior.

By default, nim-markdown supports CommonMark spec, which doesn't support strikethrough. As of now, nim-markdown is still under development on expanding all features defined in GFM.

For now, you can open experimental GFM features by specifying a config:

```nim
import markdown

echo markdown("* ~~da~~", initGfmConfig())
```

Output:

```
<ul>
<li><del>da</del></li>
</ul>
```

See [document](https://www.soasme.com/nim-markdown/markdown.html#markdown%2Cstring%2CMarkdownConfig%2CToken).
