### ISSUE TITLE
htmlEntityToUtf8 adds around 600 kb to binary size with -d:release on Windows

### ISSUE THREAD

**Issue by metagn** [soasme/nim-markdown#44]
https://github.com/soasme/nim-markdown/blob/master/src/markdownpkg/entities.nim

Tested by manually removing its use in my local Nimble instance:

```nim
# markdown.nim
proc escapeHTMLEntity*(doc: string): string =
  var entities = doc.findAll(re"&([^;]+);")
  result = doc
  for entity in entities:
    if not IGNORED_HTML_ENTITY.contains(entity):
      let utf8Char = entity.htmlEntityToUtf8
```

Size of small website builder compiled with -d:release:

![image](https://user-images.githubusercontent.com/10591326/72986961-6e4ed580-3dfa-11ea-8f20-35a5d41221e5.png)

```nim
    if not IGNORED_HTML_ENTITY.contains(entity):
      let utf8Char = entity#.htmlEntityToUtf8
```

Same compilation settings:

![image](https://user-images.githubusercontent.com/10591326/72987018-8de5fe00-3dfa-11ea-867a-c7ea28b23c59.png)

Converting this to a constant table should save ~~a large amount of~~ space. A build option to turn it off might work as a temporary option though, like `-d:markdownNoEntities`

**Update:** Tried changing it to a hash table, it apparently does not save much space:

![image](https://user-images.githubusercontent.com/10591326/72987583-c0442b00-3dfb-11ea-8abf-44978fa955b0.png)

This makes sense because of the way case/of is optimized (case/of itself is probably faster than a hash table), but I expected it to have a bigger impact. My mistake.

What does save a little more space than that though is using an array of tuples and checking for equality every single time instead of hashes, sacrificing speed:

![image](https://user-images.githubusercontent.com/10591326/72987777-1fa23b00-3dfc-11ea-9e8c-43d85b9c7e0a.png)

This is just a bad idea for performance. I would really rather just not have all this in my binary.

Forgot to mention this is on Nim 1.0.4.

**Comment by soasme** [comment]
This was a workaround due to nimlang std library function [`htmlparser.entityToUtf8`](https://nim-lang.org/docs/htmlparser.html#entityToUtf8%2Cstring) can't translate all of the html entities defined in [commonmark spec](https://spec.commonmark.org/0.29/#entity-and-numeric-character-references), in particular, <https://html.spec.whatwg.org/multipage/entities.json>.

The current Nim implementation of converting entities is also through a hash, [(source code)](https://github.com/nim-lang/Nim/blob/5732bb41efb32e1f875626fc7864e878edfab7a3/lib/pure/htmlparser.nim#L401), btw.

I'll create an upstream issue to Nimlang reporting the issue and hope more characters can be added to language std library. If the proposal can be approved, then this module is no longer needed in the library.

Adding an option `markdownNoEntities` will make nim-markdown incompatible to the commonmark spec. I think correctness is very important as well. 

Another way is to diff the above entities.json with the current entity set in Nim implementation and introduce those missing to nim-markdown. This is probably a solution that can both ensure correctness and reduce binary size without harm the performance.
